name: Shift Solutions
favicon: null
layout_spectrum: 0.9709221525117755
typography_spectrum: 0.7394451012369245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3868625417817384
  lightness: 0.218550699763
  saturation: 0.31731488299556077
  rhythmicContrast: 0.09666290367022157
purpose: []
